run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs:
    - vendor
  skip-files: []
  modules-download-mode: readonly|release|vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable-all: true
  disable:
    - lll
    - maligned
    - prealloc
    - gochecknoglobals

run:
  skip-dirs:
    - test/testdata_etc

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "G402: TLS InsecureSkipVerify set true"
      linters:
        - gosec

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.15.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - glide install
