# cm.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: helb
data:
  config.yaml: |
    dns:
      host: ""
      port: 53
    proxy:
      host: ""
    tls:
      key:
      secret:
    domain: <YOUR DOMAIN>
    subDomain: <YOUR SUBDOMAIN>
    ttl: 600s
    syncPeriod: 300s
    providers:
      nameserver:
        dnspod:
          token: <YOUR DNSPOD API ID AND TOKEN>
      ip:
        static:
          ip: <YOUR IP>

