kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helb
rules:
- apiGroups: [""]
  resources: ["services", "services/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes", "secrets"]
  verbs: ["list","watch","get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helb
subjects:
- kind: ServiceAccount
  name: helb
  namespace: default
roleRef:
  kind: ClusterRole
  name: helb
  apiGroup: rbac.authorization.k8s.io