# svc.yml
kind: Service
apiVersion: v1
metadata:
  name: helb
spec:
  selector:
    app: helb
  externalIPs:
  - <YOUR IP>
  sessionAffinity: None
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https

